'use strict';

module.exports = {
  AccessToken: [],
  ACL: [],
  Role: [
    {
      'name': 'admin',
    }, {
      'name': 'normal',
    }, {
      'name': 'premium',
    },
  ],
  RoleMapping: [
    {
      principalType: 'USER',
      principalId: 1,
      roleId: 1,
    },
  ],
  user: [
    {
      'firstName': 'Tony',
      'lastName': 'Stark',
      'username': 'ironman',
      'password': 'ironman',
      'emailVerified': true,
      'email': 'ironman@test.com',
      'fame': [{
        'id': 1,
        'value': 84,
        'symbol': 'BTC',
      }],
    }, {
      'firstName': 'Peter',
      'lastName': 'Parker',
      'username': 'spiderman',
      'password': 'spiderman',
      'emailVerified': true,
      'email': 'spiderman@test.com',
      'fame': [{
        'id': 3,
        'value': 100,
        'symbol': 'XRP',
      }],
    }, {
      'firstName': 'Bruce',
      'lastName': 'Banner',
      'username': 'hulk',
      'password': 'hulk',
      'emailVerified': true,
      'email': 'hulk@test.com',
      'fame': [{
        'id': 2,
        'value': 2,
        'symbol': 'ETH',
      }],
    }, {
      'firstName': 'Thor',
      'lastName': 'Skgar',
      'username': 'thor',
      'password': 'thor',
      'emailVerified': true,
      'email': 'thor@test.com',
      'fame': [{
        'id': 3,
        'value': 100,
        'symbol': 'BCH',
      }],
    },
  ],
  coin: [
    {
      'name': 'Bitcoin',
      'symbol': 'BTC',
      'totalSupply': 17089700.0,
    }, {
      'name': 'Ethereum',
      'symbol': 'ETH',
      'totalSupply': 100035260.0,
    }, {
      'name': 'Ripple',
      'symbol': 'XRP',
      'totalSupply': 99991958570.0,
    }, {
      'name': 'Bitcoin Cash',
      'symbol': 'BCH',
      'totalSupply': 17180038.0,
    }, {
      'name': 'EOS',
      'symbol': 'EOS',
      'totalSupply': 900000000.0,
    }, {
      'name': 'Litecoin',
      'symbol': 'LTC',
      'totalSupply': 56952723.0,
    }, {
      'name': 'Stellar',
      'symbol': 'XLM',
      'totalSupply': 104025824192.0,
    }, {
      'name': 'Cardano',
      'symbol': 'ADA',
      'totalSupply': 31112483745.0,
    }, {
      'name': 'IOTA',
      'symbol': 'MIOTA',
      'totalSupply': 2779530283.0,
    }, {
      'name': 'TRON',
      'symbol': 'TRX',
      'totalSupply': 100000000000.0,
    },
  ],
  advisory: [],
  // 'disputa': [],
  // instruccion: [],
  offer: [],
  comment: [
    {
      content: 'Hola, hay alguien',
      modelName: 'signal',
      modelId: 1,
      status: true,
      userId: 1,
    }, {
      content: 'hay alguien',
      modelName: 'signal',
      modelId: 1,
      status: true,
      userId: 1,
    }, {
      content: 'en serio, hay alguien!!! X(',
      modelName: 'signal',
      modelId: 1,
      status: true,
      userId: 1,
    }, {
      content: 'Hola, hay alguien',
      modelName: 'news',
      modelId: 2,
      status: true,
      userId: 2,
    },
  ],
  answer: [
    {
      content: 'yo te estoy respondiendo',
      modelName: 'signal',
      modelId: 2,
      commentId: 1,
      status: true,
      userId: 3,
    }, {
      content: 'pero no me escuchas',
      modelName: 'signal',
      modelId: 2,
      commentId: 1,
      status: true,
      userId: 3,
    }, {
      content: 'yo te estoy respondiendo',
      modelName: 'signal',
      modelId: 2,
      commentId: 2,
      status: true,
      userId: 4,
    }, {
      content: 'pero no me escuchas',
      modelName: 'signal',
      modelId: 2,
      commentId: 1,
      status: true,
      userId: 3,
    },
  ],
  market: [],
  project: [],
  title: [
    {
      'name': 'Detalle del proyecto ',
    }, {
      'name': 'Introducción',
      'correspondence': 1,
      'link': 'introduccion.html',
    }, {
      'name': 'Detalles de la tecnología',
      'correspondence': 1,
      'link': 'detallestecnologia.html',
    }, {
      'name': 'Road-map y producto mínimo viable',
      'correspondence': 1,
      'link': 'road-mapproductominimoviable.html',
    }, {
      'name': 'Contrapartes en la tecnología centralizada',
      'correspondence': 1,
      'link': 'contrapartestecnologiacentralizada.html',
    }, {
      'name': 'Necesidad de ser descentralizado',
      'correspondence': 1,
      'link': 'necesidadserdescentralizado.html',
    }, {
      'name': 'Necesidad',
      'correspondence': 1,
      'link': 'necesidad.html',
    }, {
      'name': 'Nicho de mercado',
      'correspondence': 1,
      'link': 'nichomercado.html',
    }, {
      'name': 'Diferencia competitiva',
      'correspondence': 1,
      'link': 'diferenciacompetitiva.html',
    }, {
      'name': 'Consideraciones',
      'correspondence': 1,
      'link': 'consideraciones1.html',
    }, {
      'name': 'Marketing',
    }, {
      'name': 'Calidad del equipo encargado',
      'correspondence': 11,
      'link': 'calidadequipoencargado.html',
    }, {
      'name': 'Medios de prensa',
      'correspondence': 11,
      'link': 'mediosprensa.html',
    }, {
      'name': 'Asociaciones',
      'correspondence': 11,
      'link': 'asociaciones.html',
    }, {
      'name': 'Calidad de imagen',
      'correspondence': 11,
      'link': 'calidadimagen.html',
    }, {
      'name': 'Consideraciones',
      'correspondence': 11,
      'link': 'consideraciones11.html',
    }, {
      'name': 'Redes sociales',
    }, {
      'name': 'Crecimiento',
      'correspondence': 17,
      'link': 'crecimiento.html',
    }, {
      'name': 'Reacción de seguidores',
      'correspondence': 17,
      'link': 'reaccionseguidores.html',
    }, {
      'name': 'Implicación',
      'correspondence': 17,
      'link': 'implicacion.html',
    }, {
      'name': 'Consideraciones',
      'correspondence': 17,
      'link': 'consideraciones17.html',
    }, {
      'name': 'Oferta Vs Demanda',
    }, {
      'name': 'Minería de datos',
      'correspondence': 22,
      'link': 'mineriadatos.html',
    }, {
      'name': 'Política inflacionaria',
      'correspondence': 22,
      'link': 'politicainflacionaria.html',
    }, {
      'name': 'Uso de tokens e indicador NVT',
      'correspondence': 22,
      'link': 'usotokensindicadornvt.html',
    }, {
      'name': 'Estimación del tamaño de mercado',
      'correspondence': 22,
      'link': 'estimaciontamanomercado.html',
    }, {
      'name': 'Comparación entre oferta y demanda',
      'correspondence': 22,
      'link': 'comparacionofertademanda.html',
    }, {
      'name': 'Consideraciones',
      'correspondence': 22,
      'link': 'consideraciones22.html',
    }, {
      'name': 'Equipo',
    }, {
      'name': 'Directivos',
      'correspondence': 29,
      'link': 'directivos.html',
    }, {
      'name': 'Asesores',
      'correspondence': 29,
      'link': 'asesores.html',
    }, {
      'name': 'Frecuencia de actualizaciones en Github',
      'correspondence': 29,
      'link': 'recuenciaactualizacionesgithub.html',
    }, {
      'name': 'Consideraciones',
      'correspondence': 29,
      'link': 'consideraciones29.html',
    }, {
      'name': 'Conclusiones',
    }, {
      'name': 'Conclusion',
      'correspondence': 34,
      'link': 'conclusion.html',
    },
  ],
  idea: [
    {
      'content': 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido' +
        ' usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado',
      'qualidication': 3,
      'titleId': 35,
      'coinId': 2,
      'userId': 1,
    }, {
      'content': 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido' +
        ' usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado',
      'qualidication': 2,
      'titleId': 35,
      'coinId': 3,
      'userId': 2,
    }, {
      'content': 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido' +
        ' usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado',
      'qualidication': 1,
      'titleId': 35,
      'coinId': 1,
      'userId': 3,
    },
  ],
  chatroom: [],
  chat: [],
  news: [
    {
      'title': 'El servicio gratuito de Google traduce instantáneamente palabras',
      'content': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'coinType': 'BTC',
      'guessCoin': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras <img src="dropbox:1-1532253786453.jpeg:" alt="" width="480" height="494" /></span></p>',
      'guessPrice': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, <img src="dropbox:1-1532253786453.jpeg:" alt="" width="480" height="494" /></span></p>',
      'userId': 1,
      'coinId': 1,
      'image': '1-perfil-1.png',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 2,
      'coinId': 2,
      'image': '2-perfil-2.jpeg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 3,
      'coinId': 2,
      'image': '3-perfil-3.jpeg',
    }, {
      'title': 'El servicio gratuito de Google traduce instantáneamente palabras',
      'content': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'coinType': 'BTC',
      'guessCoin': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras <img src="dropbox:1-1532253786453.jpeg:" alt="" width="480" height="494" /></span></p>',
      'guessPrice': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras <img src="dropbox:1-1532253786453.jpeg:" alt="" width="480" height="494" /></span></p>',
      'userId': 1,
      'coinId': 1,
      'image': '1-perfil-4.jpg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 2,
      'coinId': 2,
      'image': '2-perfil-5.jpg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 3,
      'coinId': 2,
      'image': '3-perfil-6.jpg',
    }, {
      'title': 'El servicio gratuito de Google traduce instantáneamente palabras',
      'content': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'coinType': 'BTC',
      'guessCoin': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras <img src="dropbox:1-1532253786453.jpeg:" alt="" width="480" height="494" /></span></p>',
      'guessPrice': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras <img src="dropbox:1-1532253786453.jpeg:" alt="" width="480" height="494" /></span></p>',
      'userId': 1,
      'coinId': 1,
      'image': '1-perfil-7.jpg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 2,
      'coinId': 2,
      'image': '2-perfil-8.jpg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 3,
      'coinId': 2,
      'image': '3-perfil-9.jpg',
    }, {
      'title': 'El servicio gratuito de Google traduce instantáneamente palabras',
      'content': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'coinType': 'BTC',
      'guessCoin': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'guessPrice': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'userId': 1,
      'coinId': 1,
      'image': '1-perfil-10.jpeg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 2,
      'coinId': 2,
      'image': '2-perfil-11.jpeg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 3,
      'coinId': 2,
      'image': '3-perfil-12.jpg',
    }, {
      'title': 'El servicio gratuito de Google traduce instantáneamente palabras',
      'content': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'coinType': 'BTC',
      'guessCoin': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'guessPrice': '<p><span class=\"st\">El servicio gratuito de Google traduce instantáneamente palabras, frases y páginas web del español a más de 100 idiomas y viceversa.</span></p>',
      'userId': 1,
      'coinId': 1,
      'image': '1-perfil-13.jpg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 2,
      'coinId': 2,
      'image': '2-perfil-14.jpg',
    }, {
      'title': '¿Qué es Lorem Ipsum?',
      'content': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'coinType': 'ETH',
      'guessCoin': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'guessPrice': '<h2>¿Qué es Lorem Ipsum?</h2>\n<p></p>\n<p><strong>Lorem Ipsum</strong> es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)</p>',
      'userId': 3,
      'coinId': 2,
      'image': '3-perfil-15.jpg',
    },
  ],
  // notification: [],
  follow: [
    {
      'userId': 1,
      'followerId': 2,
    }, {
      'userId': 1,
      'followerId': 3,
    }, {
      'userId': 1,
      'followerId': 4,
    }, {
      'userId': 2,
      'followerId': 1,
    },
  ],
  signal: [
    {
      'offer': true,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'BTC',
      'currentExchange': 'USD',
      'userId': 1,
      'expiration': '2018-12-24',
      'coinId': 1,
      'image': '1-perfil-1.png',
    }, {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 2,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '2-perfil-2.jpeg',
    },
    {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 3,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '3-perfil-3.jpeg',
    }, {
      'offer': true,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'BTC',
      'currentExchange': 'USD',
      'userId': 1,
      'expiration': '2018-12-24',
      'coinId': 1,
      'image': '1-perfil-4.jpg',
    }, {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 2,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '2-perfil-5.jpg',
    },
    {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 3,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '3-perfil-6.jpg',
    }, {
      'offer': true,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'BTC',
      'currentExchange': 'USD',
      'userId': 1,
      'expiration': '2018-12-24',
      'coinId': 1,
      'image': '1-perfil-7.jpg',
    }, {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 2,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '2-perfil-8.jpg',
    },
    {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 3,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '3-perfil-9.jpg',
    }, {
      'offer': true,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'BTC',
      'currentExchange': 'USD',
      'userId': 1,
      'expiration': '2018-12-24',
      'coinId': 1,
      'image': '1-perfil-10.jpeg',
    }, {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 2,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '2-perfil-11.jpeg',
    },
    {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 3,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '3-perfil-12.jpg',
    }, {
      'offer': true,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'BTC',
      'currentExchange': 'USD',
      'userId': 1,
      'expiration': '2018-12-24',
      'coinId': 1,
      'image': '1-perfil-13.jpg',
    }, {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 2,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '2-perfil-14.jpg',
    },
    {
      'offer': false,
      'investmentType': 'POW',
      'fundamentalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'technicalAnalysis': '<p>Considero, que al ser una inclusion de imagenes e iconografia tradicional, este tipo de noticias impulsa y ayuda a el interes de los usuarios, estimo un analisis tecnico de este tipo:</p>\n<p><img src=\"dropbox:7-1528146678779.png:\" alt=\"\" /></p>\n<p>Asi que esperamos una subida poderosa</p>',
      'exitStrategy': 'string',
      'coinType': 'ETH',
      'currentExchange': 'USD',
      'userId': 3,
      'expiration': '2018-12-31',
      'coinId': 2,
      'image': '3-perfil-15.jpg',
    },
  ],
  point: [
    {
      'name': 'entrada',
    }, {
      'name': 'salida',
    }, {
      'name': 'stoploss',
    },
  ],
  position: [
    {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 1,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 1,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 1,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 2,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 2,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 2,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 3,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 3,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 3,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 4,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 4,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 4,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 5,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 5,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 5,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 6,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 6,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 6,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 7,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 7,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 7,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 8,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 8,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 8,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 9,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 9,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 9,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 10,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 10,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 10,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 11,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 11,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 11,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 12,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 12,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 12,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 13,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 13,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 13,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 14,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 14,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 14,
      'pointId': 3,
    }, {
      'value': 8830,
      'capitalPercentage': 15,
      'signalId': 15,
      'pointId': 1,
    }, {
      'value': 8324,
      'capitalPercentage': 40,
      'signalId': 15,
      'pointId': 2,
    }, {
      'value': 8322,
      'capitalPercentage': 20,
      'signalId': 15,
      'pointId': 3,
    },
  ],
  transaction: [],
  request: [],
  complaint: [],
  userIdentity: [],
  userCredential: [],
};

